web/router.ex
defmodule Churchspace.Router do
  use Churchspace.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Churchspace do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/manage", PageController, :manage
  end

  scope "/", Churchspace.Display, as: :view do
    pipe_through :browser

    resources "/events", EventController, only: [:index, :show] do
      get "/index", PostController, :index
      get "/export", EventController, :export, as: :export
      get "/:id", PostController, :show
    end
  end

  scope "/manage", Churchspace do
    pipe_through :browser

    resources "/posts", PostController
    resources "/events", EventController do
      # For event posts.
      resources "/posts", PostController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Churchspace do
  #   pipe_through :api
  # end
end

web/controllers/event_viewer_controller.ex
defmodule Churchspace.EventViewerController do
  use Churchspace.Web, :controller

  alias Churchspace.Event
  alias Churchspace.Post

  def index(conn, _params) do
    events = Repo.all(Event)
    render(conn, "index.html", events: events)
  end

  def show(conn, %{"id" => id}) do
    event = Repo.get!(Event, id)
    posts =
      event
      |> assoc(:posts)
      |> Repo.all()
    render(conn, "show.html", event: event, posts: posts)
  end
end

web/views/event_viewer_view.ex
defmodule Churchspace.EventViewerView do
  use Churchspace.Web, :view
end

web/templates/event_viewer/index.html.eex
<h2>Listing events</h2>

<table class="table">
  <thead>
    <tr>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for event_viewer <- @events do %>
    <tr>

      <td class="text-right">
        <%= link "Show", to: event_viewer_path(@conn, :show, event_viewer), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New event viewer", to: event_viewer_path(@conn, :new) %>

web/templates/event_viewer/show.html.eex
<h2>Show event viewer</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @event.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @event.description %>
  </li>

  <li>
    <strong>Posts:</strong>
    <%= link "Posts", to: event_post_path(@conn, :index, @event) %>
  </li>

</ul>

<ul>
<%= for post <- @posts do %>
  <li><%= post.title %>: <%= post.parent_id %></li>
<% end %>
</ul>

<%= link "Back", to: event_viewer_path(@conn, :index) %>